import Sqtri.Upper
import Sqtri.Data.M4.All

/-! Generated by `gen/series.py`. -/

namespace SquarePacking.Tri

def sq_M4 : Fin 7 → Sq := ![⟨q (1/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩]

theorem minSideTri_7 : minSideTri 7 = 4 + 2 / Real.sqrt 3 := by
  have hL : M4.L.val = 4 + 2 / Real.sqrt 3 := by
    rw [two_div_sqrt3]; simp [M4.L]
  rw [← hL]
  apply minSideTri_eq
  · exact packs_of_axisPackB 7 M4.L sq_M4 (by decide +kernel)
  · exact le_of_checks 7 M4.L M4.yTop M4.pts (yTop_val (by decide +kernel)) M4.weights
      (by decide +kernel) M4.tree0 M4.tree1 M4.tree2 M4.check0 M4.check1 M4.check2

end SquarePacking.Tri
