import Sqtri.Upper
import Sqtri.Data.M5.All

/-! Generated by `gen/series.py`. -/

namespace SquarePacking.Tri

def sq_M5 : Fin 11 → Sq := ![⟨q (1/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩]

theorem minSideTri_11 : minSideTri 11 = 5 + 2 / Real.sqrt 3 := by
  have hL : M5.L.val = 5 + 2 / Real.sqrt 3 := by
    rw [two_div_sqrt3]; simp [M5.L]
  rw [← hL]
  apply minSideTri_eq
  · exact packs_of_axisPackB 11 M5.L sq_M5 (by decide +kernel)
  · exact le_of_checks 11 M5.L M5.yTop M5.pts (yTop_val (by decide +kernel)) M5.weights
      (by decide +kernel) M5.tree0 M5.tree1 M5.tree2 M5.check0 M5.check1 M5.check2

end SquarePacking.Tri
