import Sqtri.Upper
import Sqtri.Data.M6.All

/-! Generated by `gen/series.py`. -/

namespace SquarePacking.Tri

def sq_M6 : Fin 16 → Sq := ![⟨q (1/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (11/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (5/3), q (9/2) 0, q 1 0, q 0 0⟩]

theorem minSideTri_16 : minSideTri 16 = 6 + 2 / Real.sqrt 3 := by
  have hL : M6.L.val = 6 + 2 / Real.sqrt 3 := by
    rw [two_div_sqrt3]; simp [M6.L]
  rw [← hL]
  apply minSideTri_eq
  · exact packs_of_axisPackB 16 M6.L sq_M6 (by decide +kernel)
  · exact le_of_checks 16 M6.L M6.yTop M6.pts (yTop_val (by decide +kernel)) M6.weights
      (by decide +kernel) M6.tree0 M6.tree1 M6.tree2 M6.check0 M6.check1 M6.check2

end SquarePacking.Tri
