import Sqtri.Upper
import Sqtri.Data.M7.All

/-! Generated by `gen/series.py`. -/

namespace SquarePacking.Tri

def sq_M7 : Fin 22 → Sq := ![⟨q (1/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (11/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (13/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (5/3), q (9/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (5/3), q (9/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (6/3), q (11/2) 0, q 1 0, q 0 0⟩]

theorem minSideTri_22 : minSideTri 22 = 7 + 2 / Real.sqrt 3 := by
  have hL : M7.L.val = 7 + 2 / Real.sqrt 3 := by
    rw [two_div_sqrt3]; simp [M7.L]
  rw [← hL]
  apply minSideTri_eq
  · exact packs_of_axisPackB 22 M7.L sq_M7 (by decide +kernel)
  · exact le_of_checks 22 M7.L M7.yTop M7.pts (yTop_val (by decide +kernel)) M7.weights
      (by decide +kernel) M7.tree0 M7.tree1 M7.tree2 M7.check0 M7.check1 M7.check2

end SquarePacking.Tri
