import Sqtri.Upper
import Sqtri.Data.M8.All

/-! Generated by `gen/series.py`. -/

namespace SquarePacking.Tri

def sq_M8 : Fin 29 → Sq := ![⟨q (1/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (11/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (13/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (15/2) (1/3), q (1/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (11/2) (2/3), q (3/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (9/2) (3/3), q (5/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (7/2) (4/3), q (7/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (5/3), q (9/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (5/3), q (9/2) 0, q 1 0, q 0 0⟩,
  ⟨q (5/2) (5/3), q (9/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (6/3), q (11/2) 0, q 1 0, q 0 0⟩,
  ⟨q (3/2) (6/3), q (11/2) 0, q 1 0, q 0 0⟩,
  ⟨q (1/2) (7/3), q (13/2) 0, q 1 0, q 0 0⟩]

theorem minSideTri_29 : minSideTri 29 = 8 + 2 / Real.sqrt 3 := by
  have hL : M8.L.val = 8 + 2 / Real.sqrt 3 := by
    rw [two_div_sqrt3]; simp [M8.L]
  rw [← hL]
  apply minSideTri_eq
  · exact packs_of_axisPackB 29 M8.L sq_M8 (by decide +kernel)
  · exact le_of_checks 29 M8.L M8.yTop M8.pts (yTop_val (by decide +kernel)) M8.weights
      (by decide +kernel) M8.tree0 M8.tree1 M8.tree2 M8.check0 M8.check1 M8.check2

end SquarePacking.Tri
